### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by ghost** [kengkeelim/bwa-u4-feature-request#6]
Satisfactory

Good job, your technical design and caveat analysis are sufficient for another programmer reading your proposal to be able to implement your feature as well as make informed decisions about possible caveats.

That being said, I would recommend doing a little more research next time. Chances are, if you're writing two methods to do the job of a single method, there might be a better way to do things.

**Comment by kengkeelim** [comment]
Thank you for your advice, Steve.

"...if you're writing two methods to do the job of a single method, there might be a better way to do things."
^^^
This is a good one to remember.
